server:
  port: 8080

spring:

  application:
    name: spring-aws-sqs-example

aws:
  accessKey: test
  secretKey: test
  region: us-east-1
  host: http://localhost:4566
  sqs:
    queueExampleUrl: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sqs-example-queue
    queueExampleName: sqs-example-queue
