name: spring-aws-sqs-example CI Build

on:
  pull_request:
    branches: [master]
    paths:
      - "spring-aws-sqs-example/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:

  integration-tests:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-aws-sqs-example
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build and analyze
        run: ./gradlew clean build

  health-check:
    name: Health Check on Services
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Resolve docker compose container names
        run: ./.github/scripts/extract-compose-containers.sh ./spring-aws-sqs-example/compose.yaml

      - name: Start docker compose stack
        run: docker compose -f ./spring-aws-sqs-example/compose.yaml up -d --build

      - name: Verify container health
        run: ./.github/scripts/check-container-health.sh "${{ steps.services.outputs.services }}"

      - name: Cleanup Docker
        if: always()
        run: |
          docker compose -f ./spring-aws-sqs-example/compose.yaml down -v || true